/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import bank.IGiaoDich;
import bean.TaiKhoan;
import java.rmi.Naming;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class frmChuyenTien extends javax.swing.JFrame {

    /**
     * Creates new form frmChuyenTien
     */
    private IGiaoDich gd;
    private TaiKhoan tk;
    
    public frmChuyenTien() {
        try {
            initComponents();
            gd = (IGiaoDich) Naming.lookup("rmi://localhost/GiaoDich");
            tk = Main.getUser();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void formatMoney()
    {
        String st = txtSotien.getText().trim().replaceAll(",", "");
        try {
            long tien = Long.parseLong(st);
            txtSotien.setText(new DecimalFormat("###,###,###,###").format(tien));
        } catch (Exception e) {
            lblMess.setText("Chỉ được nhập chữ số!");
            return;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPre = new javax.swing.JButton();
        btnChuyen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSotien = new javax.swing.JTextField();
        btn100k = new javax.swing.JButton();
        btn200k = new javax.swing.JButton();
        btn500k = new javax.swing.JButton();
        btn3tr = new javax.swing.JButton();
        btn1tr = new javax.swing.JButton();
        btn2tr = new javax.swing.JButton();
        lblMess = new javax.swing.JLabel();
        txtStkNhan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ATM");

        btnPre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPre.setText("Quay Lại");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnChuyen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChuyen.setText("Chuyển tiền");
        btnChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhập Số tiền chuyển:");

        txtSotien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSotien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSotien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSotienKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSotienKeyReleased(evt);
            }
        });

        btn100k.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn100k.setText("100,000");
        btn100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100kActionPerformed(evt);
            }
        });

        btn200k.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn200k.setText("200,000");
        btn200k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200kActionPerformed(evt);
            }
        });

        btn500k.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn500k.setText("500,000");
        btn500k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500kActionPerformed(evt);
            }
        });

        btn3tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3tr.setText("3,000,000");
        btn3tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3trActionPerformed(evt);
            }
        });

        btn1tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1tr.setText("1,000,000");
        btn1tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1trActionPerformed(evt);
            }
        });

        btn2tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2tr.setText("2,000,000");
        btn2tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2trActionPerformed(evt);
            }
        });

        lblMess.setForeground(new java.awt.Color(255, 0, 0));
        lblMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtStkNhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStkNhan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStkNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStkNhanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStkNhanKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số Tài khoản nhận:");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 153, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(277, 327, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSotien, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(txtStkNhan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn500k, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn100k, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn200k, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn1tr, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn2tr, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn3tr, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStkNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMess, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn100k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn200k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn500k))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1tr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2tr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3tr)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChuyen)
                    .addComponent(btnPre))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        new frmATM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenActionPerformed
        try {
            String stkNhan = txtStkNhan.getText().trim();
            if(stkNhan.isEmpty() || "".equals(stkNhan)){
                lblMess.setText("Vui lòng nhập số tài khoản nhận tiền!");
                return;
            }
            
            String st = txtSotien.getText().trim().replaceAll(",", "");
            if(st.isEmpty() || "".equals(st)){
                lblMess.setText("Vui lòng nhập số tiền cần rút!");
                return;
            }

            long sotien;

            try {
                sotien = Long.parseLong(st);
            } catch (Exception e) {
                lblMess.setText("Chỉ được nhập chữ số!");
                return;
            }

            if(tk.getSoDu() < sotien){
                lblMess.setText("Số tiền trong tài khoản không đủ để giao dịch!");
                return;
            }
            
            int result = gd.ChuyenTien(tk.getSoTaiKhoan(), stkNhan, sotien);

            if(result == -5){
                lblMess.setText("Không tìm thấy số tài khoản nhận!");
                return;
            }
            
            if(result == -3){
                lblMess.setText("Số tiền chuyển phải lớn hơn 0!");
                return;
            }
            
            if(result == -2){
                lblMess.setText("Tài khoản đã bị vô hiệu hóa!");
                return;
            }
            
            if(result == -1){
                lblMess.setText("Số tiền trong tài khoản không đủ để giao dịch!");
                return;
            }

            if(result == 1){
                Main.subSoDu(sotien);
                lblMess.setText("");
                JOptionPane.showMessageDialog(null, "Giao dịch thành công");
            }
        } catch (Exception ex) {
            lblMess.setText("Giao dịch không thành công!");
        }
    }//GEN-LAST:event_btnChuyenActionPerformed

    private void txtSotienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSotienKeyPressed

    }//GEN-LAST:event_txtSotienKeyPressed

    private void txtSotienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSotienKeyReleased
        formatMoney();
    }//GEN-LAST:event_txtSotienKeyReleased

    private void btn100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100kActionPerformed
        txtSotien.setText("100,000");
    }//GEN-LAST:event_btn100kActionPerformed

    private void btn200kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200kActionPerformed
        txtSotien.setText("200,000");
    }//GEN-LAST:event_btn200kActionPerformed

    private void btn500kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500kActionPerformed
        txtSotien.setText("500,000");
    }//GEN-LAST:event_btn500kActionPerformed

    private void btn3trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3trActionPerformed
        txtSotien.setText("3,000,000");
    }//GEN-LAST:event_btn3trActionPerformed

    private void btn1trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1trActionPerformed
        txtSotien.setText("1,000,000");
    }//GEN-LAST:event_btn1trActionPerformed

    private void btn2trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2trActionPerformed
        txtSotien.setText("2,000,000");
    }//GEN-LAST:event_btn2trActionPerformed

    private void txtStkNhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStkNhanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStkNhanKeyPressed

    private void txtStkNhanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStkNhanKeyReleased
        try {
            String st = txtStkNhan.getText().trim();
            if(!st.isEmpty() && !st.equals("") && !st.equals(tk.getSoTaiKhoan().trim())){
                String name = gd.getTaiKhoan(st);
                lblName.setText(name);
            } else lblName.setText("");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtStkNhanKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100k;
    private javax.swing.JButton btn1tr;
    private javax.swing.JButton btn200k;
    private javax.swing.JButton btn2tr;
    private javax.swing.JButton btn3tr;
    private javax.swing.JButton btn500k;
    private javax.swing.JButton btnChuyen;
    private javax.swing.JButton btnPre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMess;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtSotien;
    private javax.swing.JTextField txtStkNhan;
    // End of variables declaration//GEN-END:variables
}
