/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import bank.IGiaoDich;
import bean.TaiKhoan;
import java.rmi.Naming;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class frmRutTien extends javax.swing.JFrame {

    /**
     * Creates new form frmRutTien
     */
    private IGiaoDich gd;
    
    public frmRutTien() {
        try {
            initComponents();
            gd = (IGiaoDich) Naming.lookup("rmi://localhost/GiaoDich");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void formatMoney()
    {
        String st = txtSotien.getText().trim().replaceAll(",", "");
        try {
            long tien = Long.parseLong(st);
            txtSotien.setText(new DecimalFormat("###,###,###,###").format(tien));
        } catch (Exception e) {
            lblMess.setText("Chỉ được nhập chữ số!");
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSotien = new javax.swing.JTextField();
        btn100k = new javax.swing.JButton();
        btn200k = new javax.swing.JButton();
        btn500k = new javax.swing.JButton();
        btn3tr = new javax.swing.JButton();
        btn1tr = new javax.swing.JButton();
        btn2tr = new javax.swing.JButton();
        lblMess = new javax.swing.JLabel();
        btnRutTien = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ATM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhập Số Tiền Rút");

        txtSotien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSotien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSotien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSotienKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSotienKeyReleased(evt);
            }
        });

        btn100k.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn100k.setText("100,000");
        btn100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100kActionPerformed(evt);
            }
        });

        btn200k.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn200k.setText("200,000");
        btn200k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200kActionPerformed(evt);
            }
        });

        btn500k.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn500k.setText("500,000");
        btn500k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500kActionPerformed(evt);
            }
        });

        btn3tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3tr.setText("3,000,000");
        btn3tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3trActionPerformed(evt);
            }
        });

        btn1tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1tr.setText("1,000,000");
        btn1tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1trActionPerformed(evt);
            }
        });

        btn2tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2tr.setText("2,000,000");
        btn2tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2trActionPerformed(evt);
            }
        });

        lblMess.setForeground(new java.awt.Color(255, 0, 0));
        lblMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn100k, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn200k, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn500k, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn1tr, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2tr, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3tr, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMess, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn100k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn200k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn500k))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1tr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2tr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3tr)))
                .addContainerGap())
        );

        btnRutTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRutTien.setText("Rút Tiền");
        btnRutTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutTienActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPre.setText("Quay Lại");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRutTien, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRutTien)
                    .addComponent(btnPre))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRutTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutTienActionPerformed
        try {
            String st = txtSotien.getText().trim().replaceAll(",", "");
            if(st.isEmpty() || "".equals(st)){
                lblMess.setText("Vui lòng nhập số tiền cần rút");
                return;
            }
            
            long sotien;
            
            try {
                sotien = Long.parseLong(st);
            } catch (Exception e) {
                lblMess.setText("Chỉ được nhập chữ số!");
                return;
            }
            
            TaiKhoan tk = Main.getUser();
            if(tk.getSoDu() < sotien){
                lblMess.setText("Số tiền trong tài khoản không đủ để rút!");
                return;
            }
            
            int result = gd.RutTien(tk.getSoTaiKhoan(), sotien, "Rút tiền tại ATM");
            
            if(result == -3){
                lblMess.setText("Số tiền trong tài khoản không đủ để rút!");
                return;
            }
            
            if(result == -2){
                lblMess.setText("Tài khoản đã bị khóa hoặc bị vô hiệu hóa!");
                return;
            }
            
            if(result == -1){
                lblMess.setText("Số tiền trong tài khoản không đủ để rút!");
                return;
            }

            if(result == 1){
                Main.subSoDu(sotien);
                lblMess.setText("");
                JOptionPane.showMessageDialog(null, "Giao dịch thành công");
            }
        } catch (Exception ex) {
            lblMess.setText("Giao dịch không thành công!");
        }
    }//GEN-LAST:event_btnRutTienActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        new frmATM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btn100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100kActionPerformed
        txtSotien.setText("100,000");
    }//GEN-LAST:event_btn100kActionPerformed

    private void btn200kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200kActionPerformed
        txtSotien.setText("200,000");
    }//GEN-LAST:event_btn200kActionPerformed

    private void btn500kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500kActionPerformed
        txtSotien.setText("500,000");
    }//GEN-LAST:event_btn500kActionPerformed

    private void btn3trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3trActionPerformed
        txtSotien.setText("3,000,000");
    }//GEN-LAST:event_btn3trActionPerformed

    private void btn1trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1trActionPerformed
        txtSotien.setText("1,000,000");
    }//GEN-LAST:event_btn1trActionPerformed

    private void btn2trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2trActionPerformed
        txtSotien.setText("2,000,000");
    }//GEN-LAST:event_btn2trActionPerformed

    private void txtSotienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSotienKeyReleased
        formatMoney();
    }//GEN-LAST:event_txtSotienKeyReleased

    private void txtSotienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSotienKeyPressed
        
    }//GEN-LAST:event_txtSotienKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100k;
    private javax.swing.JButton btn1tr;
    private javax.swing.JButton btn200k;
    private javax.swing.JButton btn2tr;
    private javax.swing.JButton btn3tr;
    private javax.swing.JButton btn500k;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnRutTien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMess;
    private javax.swing.JTextField txtSotien;
    // End of variables declaration//GEN-END:variables
}
